services:
  go-subtitler:
    container_name: go-subtitler
    restart: unless-stopped
    volumes:
      - /tmp:/wrk
    image: go-subtitler:latest
    entrypoint: tail -f /dev/null
    environment:
      WORK_DIRECTORY: /wkr
      LIBRETRANSLATE_HOST: libretranslate
      LIBRETRANSLATE_PORT: 5000
    depends_on:
      - libretranslate

  libretranslate:
    container_name: libretranslate
    restart: unless-stopped
    image: libretranslate/libretranslate:latest
    